### ISSUE TITLE
How can I use it to store a new item in an array ?

### ISSUE THREAD

**Issue by moeenio** [Tilak999/jsonstore.io#3]
Without having a counter variable if possible

**Comment by moeenio** [comment]
@Tilak999

**Comment by tilak999** [comment]
Currently the only possible method to insert an item in the array with out maintaining a counter is -
```
var jsonstore = require('jsonstore.io')

const TOKEN = '3c9622697a53d8b2f3cf825dc4160f7e1aad46c1a759475edeb76bce5cd33a64'

let store = new jsonstore(TOKEN)

store.read('Color').then( (data) => {
  let colors = data || []
  colors.push('purple')
  store.write('Color',colors)
  console.log(colors)
})
```
One major drawback of this method is everytime you make a new insert the whole array is fetched.

**Comment by moeenio** [comment]
Yeah, I figured it out, and am using it.
