### ISSUE TITLE
"Token is incorrect" yet it is correct and there is data stored there

### ISSUE THREAD

**Issue by Vandesm14** [Tilak999/jsonstore.io#4]
`(node:89) UnhandledPromiseRejectionWarning: Error: Token is incorrect, unable to read data.`
I have even tried using a whole new database token, but it is still spitting out the same error. Here is the code that I have (the token that it's given is correct, I've checked what the TOKEN outputs)
```javascript
const jsonstore = require('jsonstore.io');
require('dotenv').config();
var store = new jsonstore(process.env.TOKEN); // Token is not undefined
```

**Comment by tilak999** [comment]
Test the package and it is working fine. Could you please confirm if `process.env.TOKEN` returns token as a string and not an object.

**Comment by Vandesm14** [comment]
Yes, it is a string. I've also tried setting a variable and calling it like so
```javascript
var store = new jsonstore(token);
```
Still the same error

**Edit:** Could this be an issue with the jsonstore.io servers?

**Comment by tilak999** [comment]
I checked the module on my local system and also tested the same code in RunKit notebook. It is working as expected, i think there could be issue with requests sent from your system to jsonstore.io.

Runkit notebook: https://runkit.com/tilak999/5c76a0e214e80e0012ff042d

Try running the code on some other network or system.

**Comment by Vandesm14** [comment]
To my understanding, the issue is now gone. The only problem now is what jsonstore.io itself is down, which isn't an issue with the package.
